// resources/js/Pages/Dashboard.vue
<script setup lang="ts">
import { Head, Link } from "@inertiajs/vue3";
import {
    ArrowRight,
    CalendarDays,
    CheckCircle2,
    Clock3,
    FilePlus2,
    Files,
    LayoutDashboard,
    UserCheck,
    Users,
} from "@lucide/vue";
import AppLayout from "@/Layouts/AppLayout.vue";

const props = defineProps<{
    stats: Record<string, number>;
    deadlines: any[];
    clientCount: number;
    staffCount: number;
    months: any[];
    staffLanding: boolean;
    todayAttendance: any | null;
    user: any;
}>();

const labels: Record<string, string> = {
    total: "Total Berkas",
    processing: "Dalam Proses",
    completed: "Selesai",
    pending: "Pending",
};

const maxMonth = Math.max(1, ...props.months.map((x) => Number(x.incoming)));

const time = (value: string | null) =>
    value
        ? new Date(value).toLocaleTimeString("id-ID", {
              hour: "2-digit",
              minute: "2-digit",
          })
        : "-";
</script>

<template>
    <Head title="Dashboard" />
    <AppLayout>
        <main v-if="staffLanding" class="mx-auto max-w-5xl space-y-6 p-2 sm:p-4">
            <!-- Staff Landing Hero Card -->
            <section
                class="rounded-3xl p-6 text-white shadow-lg transition-all"
                :style="{ background: 'linear-gradient(135deg, var(--primary) 0%, color-mix(in srgb, var(--primary) 80%, black) 100%)' }"
            >
                <p class="text-xs sm:text-sm font-semibold opacity-90">Selamat datang kembali,</p>
                <h1 class="mt-1 text-2xl sm:text-3xl font-black tracking-tight">{{ user.fullName }}</h1>
                <span
                    class="mt-2 inline-block rounded-full bg-white/20 px-3 py-0.5 text-[10px] font-bold uppercase tracking-widest backdrop-blur-md"
                >
                    {{ user.role }}
                </span>

                <div
                    class="mt-6 grid gap-3 rounded-2xl bg-white/15 p-4 sm:p-5 backdrop-blur-sm sm:grid-cols-3 border border-white/20"
                >
                    <div>
                        <p class="text-[10px] font-bold uppercase tracking-wider opacity-80">Jadwal Kerja</p>
                        <p class="mt-1 text-lg sm:text-xl font-black">09:00 - 18:00</p>
                    </div>
                    <div>
                        <p class="text-[10px] font-bold uppercase tracking-wider opacity-80">Masuk</p>
                        <p class="mt-1 text-lg sm:text-xl font-black">
                            {{ time(todayAttendance?.checkIn) }}
                        </p>
                    </div>
                    <div>
                        <p class="text-[10px] font-bold uppercase tracking-wider opacity-80">Pulang</p>
                        <p class="mt-1 text-lg sm:text-xl font-black">
                            {{ time(todayAttendance?.checkOut) }}
                        </p>
                    </div>
                </div>

                <Link
                    href="/dashboard/pegawai/absensi/absenku"
                    class="mt-5 flex h-12 items-center justify-center gap-2 rounded-2xl bg-white font-black shadow-md transition-transform hover:scale-[1.01] active:scale-95 text-slate-900"
                    :style="{ color: 'var(--primary)' }"
                >
                    <UserCheck class="h-5 w-5" />
                    <span>
                        {{
                            todayAttendance?.checkIn
                                ? todayAttendance?.checkOut
                                    ? "Absensi Selesai"
                                    : "Absen Pulang"
                                : "Absen Masuk"
                        }}
                    </span>
                </Link>
            </section>

            <!-- Navigation Shortcuts -->
            <section class="grid gap-4 sm:grid-cols-2">
                <Link
                    href="/dashboard?view=overview"
                    class="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition-all hover:border-[var(--primary)] hover:shadow-md"
                >
                    <LayoutDashboard class="h-9 w-9" :style="{ color: 'var(--primary)' }" />
                    <h2 class="mt-4 text-lg font-black text-slate-900">Dashboard</h2>
                    <p class="mt-1 text-xs sm:text-sm text-slate-500">
                        Buka ringkasan aktivitas dan pekerjaan kantor.
                    </p>
                    <span
                        class="mt-4 inline-flex items-center gap-2 text-xs font-bold transition-transform group-hover:translate-x-1"
                        :style="{ color: 'var(--primary)' }"
                    >
                        <span>Buka Dashboard</span>
                        <ArrowRight class="h-4 w-4" />
                    </span>
                </Link>

                <Link
                    href="/dashboard/pegawai/absensi"
                    class="group rounded-3xl border border-slate-200 bg-white p-6 shadow-sm transition-all hover:border-emerald-500 hover:shadow-md"
                >
                    <Clock3 class="h-9 w-9 text-emerald-500" />
                    <h2 class="mt-4 text-lg font-black text-slate-900">Riwayat Absensi</h2>
                    <p class="mt-1 text-xs sm:text-sm text-slate-500">
                        Lihat check-in, check-out, dan riwayat kehadiran.
                    </p>
                    <span
                        class="mt-4 inline-flex items-center gap-2 text-xs font-bold text-emerald-600 transition-transform group-hover:translate-x-1"
                    >
                        <span>Buka Absensi</span>
                        <ArrowRight class="h-4 w-4" />
                    </span>
                </Link>
            </section>
        </main>

        <!-- Admin Overview Landing -->
        <main v-else class="space-y-6 p-2 sm:p-4">
            <div
                class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"
            >
                <div>
                    <p class="text-xs font-bold uppercase tracking-wider" :style="{ color: 'var(--primary)' }">
                        Ringkasan Hari Ini
                    </p>
                    <h1 class="text-xl sm:text-2xl font-black text-slate-900">Dashboard Overview</h1>
                </div>
                <div class="flex flex-wrap items-center gap-2">
                    <span
                        class="flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-3.5 py-2 text-xs font-bold text-slate-700 shadow-sm"
                    >
                        <CalendarDays class="h-4 w-4 text-slate-400" />
                        <span>
                            {{
                                new Date().toLocaleDateString("id-ID", {
                                    day: "numeric",
                                    month: "long",
                                    year: "numeric",
                                })
                            }}
                        </span>
                    </span>
                    <Link
                        href="/dashboard/jobs/new"
                        class="flex items-center justify-center gap-2 rounded-xl px-4 py-2 text-xs font-bold text-white shadow-md transition-all hover:opacity-90 active:scale-95"
                        :style="{ backgroundColor: 'var(--primary)' }"
                    >
                        <FilePlus2 class="h-4 w-4" />
                        <span>Berkas Baru</span>
                    </Link>
                </div>
            </div>

            <!-- Stats Grid -->
            <section class="grid grid-cols-2 gap-3 sm:gap-4 xl:grid-cols-4">
                <article
                    v-for="(value, key) in stats"
                    :key="key"
                    class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"
                >
                    <p class="text-xs font-bold uppercase tracking-wider text-slate-500">
                        {{ labels[key] }}
                    </p>
                    <p class="mt-2 text-2xl sm:text-3xl font-black text-slate-900">{{ value }}</p>
                </article>
            </section>

            <!-- Chart & Active Data Section -->
            <section class="grid gap-6 xl:grid-cols-3">
                <article
                    class="rounded-2xl border border-slate-200 bg-white p-5 xl:col-span-2 shadow-sm"
                >
                    <div class="flex items-center justify-between">
                        <div>
                            <h2 class="text-base sm:text-lg font-black text-slate-900">
                                Perkembangan Berkas
                            </h2>
                            <p class="text-xs text-slate-500">
                                Berkas masuk dan selesai 6 bulan terakhir.
                            </p>
                        </div>
                        <Files class="h-5 w-5" :style="{ color: 'var(--primary)' }" />
                    </div>
                    <div
                        class="mt-6 flex h-48 items-end gap-2 sm:gap-4 border-b border-slate-200 px-2"
                    >
                        <div
                            v-for="month in months"
                            :key="month.key"
                            class="flex h-full flex-1 items-end justify-center gap-1"
                        >
                            <div
                                class="w-2/5 rounded-t-md transition-all"
                                :style="{
                                    height: `${Math.max(6, (Number(month.incoming) / maxMonth) * 85)}%`,
                                    backgroundColor: 'var(--primary)',
                                }"
                                :title="`Masuk: ${month.incoming}`"
                            />
                            <div
                                class="w-2/5 rounded-t-md bg-emerald-500 transition-all"
                                :style="{
                                    height: `${Math.max(6, (Number(month.completed) / maxMonth) * 85)}%`,
                                }"
                                :title="`Selesai: ${month.completed}`"
                            />
                        </div>
                    </div>
                    <div
                        class="mt-3 grid grid-cols-6 text-center text-[11px] font-bold text-slate-500"
                    >
                        <span v-for="month in months" :key="month.key">{{
                            month.label
                        }}</span>
                    </div>
                </article>

                <article
                    class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm space-y-5"
                >
                    <h2 class="text-base sm:text-lg font-black text-slate-900">Data Aktif</h2>
                    <div class="flex items-center gap-4 rounded-xl border border-slate-100 bg-slate-50/50 p-4">
                        <div class="grid h-10 w-10 place-items-center rounded-xl bg-[var(--primary)]/10" :style="{ color: 'var(--primary)' }">
                            <Users class="h-5 w-5" />
                        </div>
                        <div>
                            <p class="text-xs font-semibold text-slate-500">Total Client</p>
                            <p class="text-2xl font-black text-slate-900">{{ clientCount }}</p>
                        </div>
                    </div>

                    <div class="flex items-center gap-4 rounded-xl border border-slate-100 bg-slate-50/50 p-4">
                        <div class="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-600">
                            <UserCheck class="h-5 w-5" />
                        </div>
                        <div>
                            <p class="text-xs font-semibold text-slate-500">Total Pegawai</p>
                            <p class="text-2xl font-black text-slate-900">{{ staffCount }}</p>
                        </div>
                    </div>
                </article>
            </section>

            <!-- Urgent Deadlines Section -->
            <section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
                <div class="flex items-center gap-2">
                    <CheckCircle2 class="h-5 w-5 text-amber-500" />
                    <h2 class="text-base sm:text-lg font-black text-slate-900">Deadline 7 Hari Ke Depan</h2>
                </div>
                <div class="mt-4 divide-y divide-slate-100">
                    <Link
                        v-for="job in deadlines"
                        :key="job.id"
                        :href="`/dashboard/jobs/${job.id}`"
                        class="flex items-center justify-between py-3 transition-colors hover:bg-slate-50/60 px-2 rounded-lg"
                    >
                        <div>
                            <p class="font-bold text-sm text-slate-800">{{ job.title }}</p>
                            <code class="text-[11px] font-semibold text-slate-500">{{ job.trackingCode }}</code>
                        </div>
                        <span
                            class="rounded-lg bg-amber-50 border border-amber-200 px-3 py-1 text-xs font-bold text-amber-800"
                        >
                            {{ job.deadline }}
                        </span>
                    </Link>
                    <p
                        v-if="!deadlines.length"
                        class="py-8 text-center text-sm text-slate-400"
                    >
                        Tidak ada deadline mendesak.
                    </p>
                </div>
            </section>
        </main>
    </AppLayout>
</template>

// src/app/(dashboard)/dashboard/page.tsx
"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";
import { useSession } from "next-auth/react";
import { StatusCards } from "@/components/dashboard/StatusCards";
import { DashboardOverview } from "@/components/dashboard/Overview";
import { Button } from "@/components/ui/button";
import { Calendar, Download, Plus, ArrowRight, LayoutDashboard, Clock, UserCheck, ClipboardList, PlaneTakeoff, UserX, Home, Receipt } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { getMyAttendanceToday } from "@/lib/actions/attendance";
import { toast } from "sonner";

export default function DashboardPage() {
  const { data: session, status } = useSession();
  const searchParams = useSearchParams();
  const [isMobile, setIsMobile] = useState(false);
  const [todayAttendance, setTodayAttendance] = useState<any>(null);
  const [loadingAttendance, setLoadingAttendance] = useState(true);

  const userRole = session?.user?.role;
  const isStaffLandingRole = userRole === "STAFFADMIN" || userRole === "OB";
  const showOverview = searchParams.get("view") === "overview";

  useEffect(() => {
    const media = window.matchMedia("(max-width: 768px)");
    const apply = () => setIsMobile(media.matches);
    apply();
    media.addEventListener("change", apply);
    return () => media.removeEventListener("change", apply);
  }, []);

  useEffect(() => {
    if (!isStaffLandingRole) return;
    const loadAttendance = async () => {
      setLoadingAttendance(true);
      const result = await getMyAttendanceToday();
      if (result.success) {
        setTodayAttendance(result.data?.attendance || null);
      } else {
        toast.error(result.error);
      }
      setLoadingAttendance(false);
    };
    loadAttendance();
  }, [isStaffLandingRole]);

  const staffGreeting = useMemo(() => {
    const fullName = session?.user?.fullName || session?.user?.name || "Pegawai";
    const now = new Date();
    const hour = now.getHours();
    if (hour >= 4 && hour < 11) return { title: "Selamat Pagi", name: fullName };
    if (hour >= 11 && hour < 15) return { title: "Selamat Siang", name: fullName };
    if (hour >= 15 && hour < 19) return { title: "Selamat Sore", name: fullName };
    return { title: "Selamat Malam", name: fullName };
  }, [session?.user?.fullName, session?.user?.name]);

  const attendanceActionLabel = loadingAttendance
    ? "Memuat..."
    : todayAttendance?.checkIn && !todayAttendance?.checkOut
      ? "Absen Pulang"
      : todayAttendance?.checkIn && todayAttendance?.checkOut
        ? "Sudah Absen"
        : "Absen Masuk";

  if (status === "loading") {
    return (
      <div className="flex min-h-[60vh] items-center justify-center">
        <div className="h-12 w-12 animate-spin rounded-full border-4 border-pink-500 border-t-transparent" />
      </div>
    );
  }

  if (isStaffLandingRole && !showOverview) {
    if (isMobile) {
      return (
        <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="relative overflow-hidden rounded-[2rem] bg-gradient-to-b from-pink-600 via-pink-600 to-pink-500 p-6 text-white shadow-2xl shadow-pink-500/20">
            <div className="flex items-start justify-between gap-4">
              <div>
                <p className="text-sm/5 text-white/80">{staffGreeting.title},</p>
                <h1 className="mt-1 text-2xl font-black">{staffGreeting.name}</h1>
                <p className="mt-1 text-xs font-bold uppercase tracking-widest text-white/70">
                  {userRole === "OB" ? "OB / Kurir" : "Staff Admin"}
                </p>
              </div>
              <div className="h-12 w-12 overflow-hidden rounded-2xl bg-white/20 ring-1 ring-white/30">
                {session?.user?.image ? (
                  <img src={session.user.image} alt="Avatar" className="h-full w-full object-cover" />
                ) : (
                  <div className="flex h-full w-full items-center justify-center text-sm font-black">
                    {(staffGreeting.name || "P").slice(0, 1).toUpperCase()}
                  </div>
                )}
              </div>
            </div>

            <div className="mt-6 rounded-2xl bg-white/15 p-4 ring-1 ring-white/20">
              <div className="flex items-center justify-between gap-3">
                <div>
                  <p className="text-xs font-black uppercase tracking-widest text-white/70">Jadwal Kerja</p>
                  <p className="mt-1 text-lg font-black">09:00 - 18:00</p>
                </div>
                <div className="text-right">
                  <p className="text-xs font-black uppercase tracking-widest text-white/70">Hari Ini</p>
                  <p className="mt-1 text-sm font-bold">
                    {new Date().toLocaleDateString("id-ID", { weekday: "short", day: "2-digit", month: "short", year: "numeric" })}
                  </p>
                </div>
              </div>

              <Link href="/dashboard/pegawai/absensi/absenku" className="mt-4 block">
                <Button
                  type="button"
                  className="h-12 w-full rounded-2xl bg-white text-pink-600 hover:bg-white/90 font-black"
                  disabled={!loadingAttendance && !!todayAttendance?.checkIn && !!todayAttendance?.checkOut}
                >
                  <UserCheck className="mr-2 h-4 w-4" />
                  {attendanceActionLabel}
                </Button>
              </Link>
            </div>
          </div>

          <div className="-mt-6 px-2">
            <div className="grid grid-cols-4 gap-3 rounded-[2rem] bg-card p-4 shadow-xl shadow-primary/10 ring-1 ring-border/60">
              <Link href="/dashboard/pegawai/absensi" className="flex flex-col items-center gap-2 rounded-2xl px-2 py-3 hover:bg-muted/40 transition-colors">
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-pink-500/10 text-pink-600">
                  <ClipboardList className="h-5 w-5" />
                </div>
                <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground text-center">Absensi</span>
              </Link>
              <button
                type="button"
                onClick={() => toast.info("Fitur koreksi absensi akan segera hadir.")}
                className="flex flex-col items-center gap-2 rounded-2xl px-2 py-3 hover:bg-muted/40 transition-colors"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-blue-500/10 text-blue-600">
                  <UserX className="h-5 w-5" />
                </div>
                <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground text-center">Koreksi</span>
              </button>
              <button
                type="button"
                onClick={() => toast.info("Fitur dinas akan segera hadir.")}
                className="flex flex-col items-center gap-2 rounded-2xl px-2 py-3 hover:bg-muted/40 transition-colors"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-amber-500/10 text-amber-600">
                  <PlaneTakeoff className="h-5 w-5" />
                </div>
                <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground text-center">Dinas</span>
              </button>
              <button
                type="button"
                onClick={() => toast.info("Fitur izin/cuti akan segera hadir.")}
                className="flex flex-col items-center gap-2 rounded-2xl px-2 py-3 hover:bg-muted/40 transition-colors"
              >
                <div className="flex h-10 w-10 items-center justify-center rounded-2xl bg-emerald-500/10 text-emerald-600">
                  <Clock className="h-5 w-5" />
                </div>
                <span className="text-[10px] font-black uppercase tracking-widest text-muted-foreground text-center">Izin</span>
              </button>
            </div>
          </div>

          <div className="mt-6 space-y-4 pb-20">
            <div className="flex items-center justify-between px-2">
              <h2 className="text-base font-black text-foreground">Absensi</h2>
              <Link href="/dashboard/pegawai/absensi" className="text-xs font-black text-pink-600">
                Lihat Semua
              </Link>
            </div>

            <div className="rounded-[2rem] bg-card p-5 shadow-sm ring-1 ring-border/60">
              <div className="grid grid-cols-2 gap-4">
                <div className="rounded-2xl bg-muted/30 p-4">
                  <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">Start Day</p>
                  <p className="mt-2 text-xl font-black text-foreground">
                    {todayAttendance?.checkIn ? new Date(todayAttendance.checkIn).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" }) : "-"}
                  </p>
                </div>
                <div className="rounded-2xl bg-muted/30 p-4">
                  <p className="text-[10px] font-black uppercase tracking-widest text-muted-foreground">End Day</p>
                  <p className="mt-2 text-xl font-black text-foreground">
                    {todayAttendance?.checkOut ? new Date(todayAttendance.checkOut).toLocaleTimeString("id-ID", { hour: "2-digit", minute: "2-digit" }) : "-"}
                  </p>
                </div>
              </div>
              <p className="mt-4 text-xs text-muted-foreground">
                {new Date().toLocaleDateString("id-ID", { weekday: "long", day: "numeric", month: "long", year: "numeric" })}
              </p>
            </div>

            <div className="fixed bottom-0 left-0 right-0 z-30 bg-background/80 backdrop-blur-xl border-t border-border/60">
              <div className="mx-auto flex max-w-lg items-center justify-around px-6 py-3">
                <Link href="/dashboard" className="flex flex-col items-center gap-1 text-pink-600">
                  <Home className="h-5 w-5" />
                  <span className="text-[9px] font-black uppercase tracking-widest">Home</span>
                </Link>
                <Link href="/dashboard/pegawai/absensi" className="flex flex-col items-center gap-1 text-muted-foreground hover:text-pink-600 transition-colors">
                  <Clock className="h-5 w-5" />
                  <span className="text-[9px] font-black uppercase tracking-widest">Absensi</span>
                </Link>
                <Link href="/dashboard/invoice" className="flex flex-col items-center gap-1 text-muted-foreground hover:text-pink-600 transition-colors">
                  <Receipt className="h-5 w-5" />
                  <span className="text-[9px] font-black uppercase tracking-widest">Invoice</span>
                </Link>
              </div>
            </div>
          </div>
        </div>
      );
    }

    return (
      <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
        <div className="max-w-3xl">
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Selamat Datang</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Pilih halaman yang ingin Anda buka setelah login.
          </p>
        </div>

        <div className="grid gap-6 md:grid-cols-2">
          <Link
            href="/dashboard?view=overview"
            className="group overflow-hidden rounded-[2rem] border border-border/60 bg-card shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
          >
            <div className="relative h-64 overflow-hidden bg-muted/20">
              <img
                src="/uploads/dashboard.png"
                alt="Dashboard"
                className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 via-slate-950/10 to-transparent" />
              <div className="absolute left-6 top-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/90 text-pink-500 shadow-lg">
                <LayoutDashboard className="h-6 w-6" />
              </div>
            </div>
            <div className="space-y-3 p-6">
              <div>
                <h2 className="text-xl font-black text-foreground">Dashboard</h2>
                <p className="mt-1 text-sm text-muted-foreground">
                  Buka ringkasan aktivitas dan monitor pekerjaan harian kantor.
                </p>
              </div>
              <div className="inline-flex items-center gap-2 text-sm font-bold text-pink-600">
                Masuk ke Dashboard
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </div>
            </div>
          </Link>

          <Link
            href="/dashboard/pegawai/absensi"
            className="group overflow-hidden rounded-[2rem] border border-border/60 bg-card shadow-sm transition-all duration-300 hover:-translate-y-1 hover:shadow-xl"
          >
            <div className="relative h-64 overflow-hidden bg-muted/20">
              <img
                src="/uploads/selfie.png"
                alt="Absensi"
                className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-slate-950/70 via-slate-950/10 to-transparent" />
              <div className="absolute left-6 top-6 flex h-12 w-12 items-center justify-center rounded-2xl bg-white/90 text-emerald-500 shadow-lg">
                <Clock className="h-6 w-6" />
              </div>
            </div>
            <div className="space-y-3 p-6">
              <div>
                <h2 className="text-xl font-black text-foreground">Absensi</h2>
                <p className="mt-1 text-sm text-muted-foreground">
                  Masuk ke halaman absensi untuk check-in, check-out, dan melihat riwayat kehadiran.
                </p>
              </div>
              <div className="inline-flex items-center gap-2 text-sm font-bold text-emerald-600">
                Buka Absensi
                <ArrowRight className="h-4 w-4 transition-transform group-hover:translate-x-1" />
              </div>
            </div>
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-8 animate-in fade-in slide-in-from-bottom-4 duration-700">
      <div className="flex flex-col gap-4 md:flex-row md:items-center md:justify-between">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Dashboard Overview</h1>
          <div className="mt-1 flex items-center gap-2">
            <span className="text-xs text-muted-foreground">Home</span>
            <span className="h-1 w-1 rounded-full bg-muted-foreground/40" />
            <span className="text-xs font-medium text-primary">Dashboard</span>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <Button variant="outline" size="sm" className="h-10 rounded-xl bg-card border-border/60 font-semibold gap-2">
            <Calendar className="h-4 w-4" />
            {new Date().toLocaleDateString("id-ID", { day: "numeric", month: "long", year: "numeric" })}
          </Button>
          <Button variant="outline" size="sm" className="h-10 rounded-xl bg-card border-border/60 font-semibold gap-2">
            <Download className="h-4 w-4" />
            Export
          </Button>
          <Button size="sm" className="h-10 rounded-xl font-semibold gap-2 shadow-lg shadow-primary/20">
            <Plus className="h-4 w-4" />
            New Document
          </Button>
        </div>
      </div>

      <StatusCards />

      <div className="space-y-8">
        <DashboardOverview />
      </div>
    </div>
  );
}
